config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
  root to: "flats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flat_params)
    if @flat.save!
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="w-50 m-auto">
<h1>Edit Flat</h1>
  <%= simple_form_for [@flat] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "Update flat", class: "btn btn-primary" %>
    <button type="submit" class="btn btn-danger"><%= link_to "Cancel", flats_path, class:"text-white text-decoration-none" %></button>
  <% end %>
</div>

app/views/flats/index.html.erb
<h1>All our flats - <%= Flat.count %></h1>
<br>
<div class="d-flex flex-wrap">
  <% @flats.each do |flat| %>
    <div class="card m-3" style="width: 18rem;">
      <div class="card-body">
        <div class="p-3">
          <h5 class="card-title"><%= flat.name %></h5>
          <p class="card-text"><%= flat.address %></p>
        </div>
        <div class="d-flex p-3">
          <p class="me-3"><i class="fa-solid fa-user"></i><%= flat.number_of_guests%></p>
          <p><i class="fa-solid fa-euro-sign"></i><%= flat.price_per_night %></p>
        </div>

      </div>
      <div class="d-flex justify-content-between btn-group btn-group-sm">
        <%= link_to "More info", flat_path(flat), class: "btn btn-primary" %>
        <%= link_to "Edit", edit_flat_path(flat), class: "btn btn-warning" %>
        <%= link_to "Delete", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="w-50 m-auto">
<h1>Add a new Flat</h1>
  <%= simple_form_for [@flat] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "Create flat", class: "btn btn-primary" %>
    <button type="submit" class="btn btn-danger"><%= link_to "Cancel", flats_path, class:"text-white text-decoration-none" %></button>
  <% end %>
</div>

app/views/flats/show.html.erb
<div>
  <img src="https://cdn.prod.website-files.com/5cd956143d256bfdfff3e85d/6317192384a7650b5ea2c72b_Airbnb%20Integration%20Header.jpg" alt="map" class="w-100">
</div>
<div class="d-flex flex-row justify-content-evenly p-3">
  <div>
    <div class="container border rounded p-3">
      <h1><%= @flat.name %></h1>
      <p><%= @flat.address %></p>
    </div>
    <div class="container border rounded p-3 my-3">
      <h3>A bit more about this flat...</h3>
      <p><%= @flat.description %></p>
    </div>
    <div class="container border rounded p-3">
      <h4>Details</h4>
      <div class="d-flex">
        <p class="me-3"><i class="fa-solid fa-user me-2"></i><%= @flat.number_of_guests%></p>
        <p class="me-3"><i class="fa-solid fa-euro-sign me-2"></i><%= @flat.price_per_night %></p>
      </div>
    </div>
  </div>
  <div>
    <div class="container border rounded p-3 mb-3">
      <h5>Book this place!</h5>
      <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">From:</span>
        <input type="text" class="form-control" placeholder="12/10/2017">
      </div>
      <div class="input-group mb-3">
        <span class="input-group-text" id="basic-addon1">To:</span>
        <input type="text" class="form-control" placeholder="18/10/2017">
      </div>
      <button class="btn btn-success">Book</button>
    </div>
    <div class="container border rounded p-2">
      <div class="d-flex flex-row justify-content-between">
        <p class="m-2">Share</p>
        <div class="d-flex">
          <p class="m-2"><i class="fa-brands fa-facebook"></i></p>
          <p class="m-2"><i class="fa-brands fa-twitter"></i></p>
          <p class="m-2"><i class="fa-brands fa-pinterest"></i></p>
          <p class="m-2"><i class="fa-solid fa-envelope"></i></p>
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <div class="d-flex justify-content-between p-3">
      <h1>Simple Airbnb</h1>
      <div class="btn btn-primary"><%= link_to "Add flat", new_flat_path, class: "btn text-white"%></div>
    </div>
    <div class="p-3"><%= yield %></div>
  </body>
</html>